wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.9
    cli_version: 0.17.8
    framework: huggingface
    huggingface_version: 4.43.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725905035
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 75
      - 91
      - 105
      3:
      - 23
      4: 3.11.9
      5: 0.17.8
      6: 4.43.3
      8:
      - 5
      13: darwin-arm64
